---
- name: Ensure Filebeat is absent before reinstalling (Debian/Ubuntu)
  ansible.builtin.apt:
    name: filebeat
    state: absent
    autoremove: yes # Удаляет также неиспользуемые зависимости
  when: ansible_os_family == 'Debian'
  tags: always # Выполнять всегда, даже если не указано явно

  
- name: Create directory for apt GPG keys
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  when: ansible_os_family == 'Debian'

- name: Download Elastic GPG key
  ansible.builtin.get_url:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    dest: /etc/apt/keyrings/elastic-8.x.asc
    mode: '0644'
    force: yes
  when: ansible_os_family == 'Debian'

- name: Add Filebeat repository (Debian/Ubuntu)
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/elastic-8.x.asc] https://artifacts.elastic.co/packages/8.x/apt stable main'
    state: present
    filename: elastic-8.x.list
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install Filebeat (Debian/Ubuntu)
  ansible.builtin.apt:
    name: filebeat
    state: present
  when: ansible_os_family == 'Debian'


#- name: Create an empty file /var/log/test
#  file:
#    path: /var/log/test
#    state: touch
##    owner: root
##    group: root
#    mode: '0644'

- name: Copy Filebeat configuration file
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: '0644'
  notify: Restart Filebeat

- name: Enable and start Filebeat service
  ansible.builtin.systemd:
    name: filebeat
    state: started
    enabled: yes
